server:
  port: 8084

spring:
  datasource:
    mysqldb: #\u6570\u636E\u6E901
      driver-class-name: com.mysql.cj.jdbc.Driver # mysql\u7684\u9A71\u52A8\u4F60\u53EF\u4EE5\u914D\u7F6E\u522B\u7684\u5173\u7CFB\u578B\u6570\u636E\u5E93com.mysql.cj.jdbc.Driver 8\u4E4B\u4E0A\u7684\u8FDE\u63A5com.mysql.jdbc.Driver  8\u4E4B\u4E0B\u7684\u8FDE\u63A5
      url: jdbc:mysql://121.4.53.134:3306/DB1?useSSL=false&characterEncoding=utf8 #\u6570\u636E\u6E90\u5730\u5740
      username: root # \u7528\u6237\u540D
      password: zhaofang1234 # \u5BC6\u7801
    oracledb: # \u6570\u636E\u6E902
      driver-class-name: oracle.jdbc.driver.OracleDriver  # mysql\u7684\u9A71\u52A8\u4F60\u53EF\u4EE5\u914D\u7F6E\u522B\u7684\u5173\u7CFB\u578B\u6570\u636E\u5E93
      url: jdbc:oracle:thin:@127.0.0.1:1521:orcl  # \u6570\u636E\u6E90\u5730\u5740
      username: sh_12345hotline # \u7528\u6237\u540D
      password: sh_12345hotline # \u5BC6\u7801

#mybatis-plus:
#  mapper-locations: classpath:/com/example/examplerecketmqdao/dao/mysql/mapping/*.xml


