

dubbo:
  application:
    name: myProvider
  registry:
    address: zookeeper://121.4.53.134:2181
    timeout: 15000

  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.example.dubbo.privide.service.impl


#这个是mater分支
#修改master分支22.46
#用idea提交代码测试
#这里是idea中提交的代码，尝试解决代码冲突

