server:
  port: 8085

spring:
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: 127.0.0.1:9200
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200
