server:
  port: 8081
spring:
  application:
    name: example-apollo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/example?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: 880604zy
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true


app:
  id: springboot-apollo
apollo:
  meta: http://localhost:8080/
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0