server:
  port: 8082
dubbo:
  application:
    name: myConsumer
  registry:
    address: zookeeper://121.4.53.134:2181
    timeout: 15000
  protocol:
    name: dubbo
    port: 20880



logging:
  level:
    root: trace